### ISSUE TITLE
Demo Library Link Order

### ISSUE THREAD

**Issue by dermont123** [Ybalrid/BtOgre2#14]
Hi,

The link order appears to be wrong for the demo when building against bullet static libs.
`
diff --git a/demo/CMakeLists.txt b/demo/CMakeLists.txt
index a6bbc8a..fb7a8fc 100644
--- a/demo/CMakeLists.txt
+++ b/demo/CMakeLists.txt
@@ -33,11 +33,11 @@ add_executable(BtOgre21DEMO main.cpp)
 #Link the required libraries
 target_link_libraries(
         BtOgre21DEMO
//+        ${BtOgre21_LIBRARIES}
         ${BULLET_LIBRARIES}
         ${OGRE_LIBRARIES}
         ${OGRE_HlmsPbs_LIBRARIES}
         ${OGRE_HlmsUnlit_LIBRARIES}
//-        ${BtOgre21_LIBRARIES}
         ${SDL2_LIBRARY}
 
 )
`
`
/media/sdb15/Development/OGRE/v2-1/BtOgre21/build/libBtOgre21.a(BtOgreGP.cpp.o): In function `BtOgre::VertexIndexToShape::createBox()':
BtOgreGP.cpp:(.text+0xd39): undefined reference to `btBoxShape::btBoxShape(btVector3 const&)'
/media/sdb15/Development/OGRE/v2-1/BtOgre21/build/libBtOgre21.a(BtOgreGP.cpp.o): In function `BtOgre::VertexIndexToShape::createCylinder()':
BtOgreGP.cpp:(.text+0xee2): undefined reference to `btCylinderShapeX::btCylinderShapeX(btVector3 const&)'
BtOgreGP.cpp:(.text+0xf36): undefined reference to `btCylinderShapeZ::btCylinderShapeZ(btVector3 const&)'
BtOgreGP.cpp:(.text+0xf76): undefined reference to `btCylinderShape::btCylinderShape(btVector3 const&)'
/media/sdb15/Development/OGRE/v2-1/BtOgre21/build/libBtOgre21.a(BtOgreGP.cpp.o): In function `BtOgre::VertexIndexToShape::createConvex()':
BtOgreGP.cpp:(.text+0x10cc): undefined reference to `btConvexHullShape::btConvexHullShape(float const*, int, int)'
/media/sdb15/Development/OGRE/v2-1/BtOgre21/build/libBtOgre21.a(BtOgreGP.cpp.o): In function `BtOgre::VertexIndexToShape::createTrimesh()':
BtOgreGP.cpp:(.text+0x11f0): undefined reference to `btTriangleMesh::btTriangleMesh(bool, bool)'
BtOgreGP.cpp:(.text+0x1354): undefined reference to `btTriangleMesh::addTriangle(btVector3 const&, btVector3 const&, btVector3 const&, bool)'
/media/sdb15/Development/OGRE/v2-1/BtOgre21/build/libBtOgre21.a(BtOgreGP.cpp.o): In function `BtOgre::VertexIndexToShape::createCapsule()':
BtOgreGP.cpp:(.text+0x1554): undefined reference to `btCapsuleShape::btCapsuleShape(float, float)'
BtOgreGP.cpp:(.text+0x15cf): undefined reference to `btCapsuleShapeX::btCapsuleShapeX(float, float)'
BtOgreGP.cpp:(.text+0x1632): undefined reference to `btCapsuleShapeZ::btCapsuleShapeZ(float, float)'
/media/sdb15/Development/OGRE/v2-1/BtOgre21/build/libBtOgre21.a(BtOgreGP.cpp.o): In function `BtOgre::AnimatedMeshToShapeConverter::createAlignedBox(unsigned char, Ogre::Vector3 const&, Ogre::Quaternion const&)':
BtOgreGP.cpp:(.text+0x389a): undefined reference to `btBoxShape::btBoxShape(btVector3 const&)'
/media/sdb15/Development/OGRE/v2-1/BtOgre21/build/libBtOgre21.a(BtOgreGP.cpp.o): In function `BtOgre::AnimatedMeshToShapeConverter::createOrientedBox(unsigned char, Ogre::Vector3 const&, Ogre::Quaternion const&)':
BtOgreGP.cpp:(.text+0x3f41): undefined reference to `btBoxShape::btBoxShape(btVector3 const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/BtOgre21DEMO.dir/build.make:104: recipe for target 'BtOgre21DEMO' failed
make[2]: *** [BtOgre21DEMO] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/BtOgre21DEMO.dir/all' failed
make[1]: *** [CMakeFiles/BtOgre21DEMO.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Ybalrid** [comment]
Hi, you can pull request your changes if you want, I'll will merge them directly ;-)

**Comment by Ybalrid** [comment]
Hi @dermont123 I think I misunderstood your first message, I thought this diff was a patch you wanted me to apply to CMakeLists.txt

So, I don't know why it is not correctly linking on your system. Can you provide me more info on the Linux distro, on how you installed Bullet ?

When you say "static lib" are you talking about BtOgre21.a, or Bullet itself?

**Comment by dermont123** [comment]
Yep commit d2d5937 resolves the problem. Thanks.

Distro ubuntu 18.04, bullet version 2.86 / 2.87 using Bullet2 api, both built statically and local install.

I'm using your version of BtOgre to build a python-ogre btogre module for Ogre v2-2 and Ogrev2-1 so the demo doesn't really affect me. 

The demo is not linking because  the link order is wrong when building against bullet static libs.  BtOgre21_LIBRARIES should come first as per your commit.

**Comment by Ybalrid** [comment]
> I'm using your version of BtOgre to build a python-ogre btogre module for Ogre v2-2 and Ogrev2-1 so the demo doesn't really affect me.

This is really interesting. Can you confirm Ogre v2-2 compatibility with this fork of BtOgre? AFAIK it's only a refactor of the texture management thing.

I've put "21" in the name, but it really should be Ogre 2. The difference here is that it works with v2 Mesh/Items. I may rename this thing `BtOgre2 ` in the near future?

**Comment by dermont123** [comment]
The demo works with v2-2 with a few minor changes.
[v22.diff.zip](https://github.com/Ybalrid/BtOgre21/files/2236680/v22.diff.zip)

**Comment by screwt** [comment]
This issue should be closed right?

**Comment by dermont123** [comment]
Yes it should be closed.

**Comment by Ybalrid** [comment]
If you still have issues with CMake, please open a new one.
